import "./globals.css";
import { Inter } from "next/font/google";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "pwr faucet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href={`https://kit.fontawesome.com/${process.env.NEXT_PUBLIC_FONTAWESOME_KEY}.css`}
          crossOrigin="anonymous"
        />
        <body className={inter.className}>{children}</body>
      </head>
    </html>
  );
}
